package com.clz.share.event.entity;
// Generated 07.09.2015 14:22:20 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventParticipantId generated by hbm2java
 */
@Embeddable
public class EventParticipantId implements java.io.Serializable {

	private long accountId;
	private String eventId;

	public EventParticipantId() {
	}

	public EventParticipantId(long accountId, String eventId) {
		this.accountId = accountId;
		this.eventId = eventId;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "event_id", nullable = false, length = 45)
	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventParticipantId))
			return false;
		EventParticipantId castOther = (EventParticipantId) other;

		return (this.getAccountId() == castOther.getAccountId())
				&& ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null
						&& castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAccountId();
		result = 37 * result + (getEventId() == null ? 0 : this.getEventId().hashCode());
		return result;
	}

}
