package com.clz.share.event.entity;
// Generated 07.09.2015 14:22:20 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import com.clz.share.sec.entity.Account;

/**
 * EventParticipant generated by hbm2java
 */
@Entity
@Table(name = "event_participant", catalog = "share")
public class EventParticipant implements java.io.Serializable {

	private EventParticipantId id;
	private Account account;
	private EventInfo eventInfo;
	private String contribution;

	public EventParticipant() {
	}

	public EventParticipant(EventParticipantId id, Account account, EventInfo eventInfo) {
		this.id = id;
		this.account = account;
		this.eventInfo = eventInfo;
	}

	public EventParticipant(EventParticipantId id, Account account, EventInfo eventInfo, String contribution) {
		this.id = id;
		this.account = account;
		this.eventInfo = eventInfo;
		this.contribution = contribution;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false) ),
			@AttributeOverride(name = "eventId", column = @Column(name = "event_id", nullable = false, length = 45) ) })
	public EventParticipantId getId() {
		return this.id;
	}

	public void setId(EventParticipantId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@OnDelete(action=OnDeleteAction.CASCADE)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@OnDelete(action=OnDeleteAction.CASCADE)
	@JoinColumn(name = "event_id", nullable = false, insertable = false, updatable = false)
	public EventInfo getEventInfo() {
		return this.eventInfo;
	}

	public void setEventInfo(EventInfo eventInfo) {
		this.eventInfo = eventInfo;
	}

	@Column(name = "contribution", length = 500)
	public String getContribution() {
		return this.contribution;
	}

	public void setContribution(String contribution) {
		this.contribution = contribution;
	}

}
