package com.clz.share.event.entity;
// Generated 14.09.2015 14:50:51 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * EventInfo generated by hbm2java
 */
@Entity
@Table(name = "event_info", catalog = "share")
public class EventInfo implements java.io.Serializable {

	private String eventId;
	private Date endDate;
	private String eventDescription;
	private Double eventLatitude;
	private String eventLocation;
	private Double eventLongitude;
	private String eventName;
	private String eventState;
	private String eventType;
	private Date startDate;
	private String city;
	private String street;
	private String postcode;
	//the detail of the address
	private String detail;
	private Long accountId;
	private Set<EventParticipant> eventParticipants = new HashSet<EventParticipant>(0);

	public EventInfo() {
	}

	public EventInfo(String eventId) {
		this.eventId = eventId;
	}

	public EventInfo(String eventId, Date endDate, String eventDescription, Double eventLatitude, String eventLocation,
			Double eventLongitude, String eventName, String eventState, String eventType, Date startDate, String city,
			String street, String postcode, String detail, Long accountId, Set<EventParticipant> eventParticipants) {
		this.eventId = eventId;
		this.endDate = endDate;
		this.eventDescription = eventDescription;
		this.eventLatitude = eventLatitude;
		this.eventLocation = eventLocation;
		this.eventLongitude = eventLongitude;
		this.eventName = eventName;
		this.eventState = eventState;
		this.eventType = eventType;
		this.startDate = startDate;
		this.city = city;
		this.street = street;
		this.postcode = postcode;
		this.detail = detail;
		this.accountId = accountId;
		this.eventParticipants = eventParticipants;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "event_id", unique = true, nullable = false, length = 45)
	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "event_description", length = 800)
	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	@Column(name = "event_latitude", precision = 22, scale = 0)
	public Double getEventLatitude() {
		return this.eventLatitude;
	}

	public void setEventLatitude(Double eventLatitude) {
		this.eventLatitude = eventLatitude;
	}

	@Column(name = "event_location", length = 200)
	public String getEventLocation() {
		return this.eventLocation;
	}

	public void setEventLocation(String eventLocation) {
		this.eventLocation = eventLocation;
	}

	@Column(name = "event_longitude", precision = 22, scale = 0)
	public Double getEventLongitude() {
		return this.eventLongitude;
	}

	public void setEventLongitude(Double eventLongitude) {
		this.eventLongitude = eventLongitude;
	}

	@Column(name = "event_name", length = 200)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "event_state", length = 10)
	public String getEventState() {
		return this.eventState;
	}

	public void setEventState(String eventState) {
		this.eventState = eventState;
	}

	@Column(name = "event_type", length = 200)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "city", length = 200)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 200)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "postcode", length = 45)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "detail", length = 200)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventInfo")
	public Set<EventParticipant> getEventParticipants() {
		return this.eventParticipants;
	}

	public void setEventParticipants(Set<EventParticipant> eventParticipants) {
		this.eventParticipants = eventParticipants;
	}

}
